stages:
  - build
  - dockerize

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE/banking-app

# -----------------------
# 1. Build Spring Boot JAR
# -----------------------
build:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar

# -----------------------
# 2. Build Docker Image
# -----------------------
docker-build:
  stage: dockerize
  image: docker:24
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA