#spring.data.mongodb.uri=mongodb://localhost:27017/bankingDB
#spring.data.mongodb.uri=mongodb://mongodb:27017/bankingDB
#spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://mongodb:27017/bankingDB}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/bankingDB}
# Actuator exposure
management.endpoints.web.exposure.include=health,info,metrics

# Show full health details
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

server.port=8081

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always